apiVersion: apps/v1
kind: Deployment
metadata:
  name: roulette-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: roulette-backend
  template:
    metadata:
      labels:
        app: roulette-backend
    spec:
      containers:
        - name: roulette-backend
          image: volumegambit/roulette-backend:ead72511d5d65eef151f5bd942b2faac8b344ffb
          env:
            - name: PORT
              value: "5002"
            - name: RPC_URL
              valueFrom:
                secretKeyRef:
                  name: roulette-secrets
                  key: RPC_URL
            - name: HOUSE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: roulette-secrets
                  key: HOUSE_ADDRESS
          ports:
            - containerPort: 5002
