apiVersion: v1
kind: Service
metadata:
  name: roulette-backend-service
spec:
  selector:
    app: roulette-backend
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
