apiVersion: v1
kind: Service
metadata:
  name: roulette-frontend-service
spec:
  selector:
    app: roulette-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
